/*
 * console.c: A dummy interactive console program.
 *
 * Author: Rohan Bari
 * Date:   2021-08-30
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_CMD_LENGTH 2048

/*
 * Display banner of the application.
 */
void display_banner(void) {
    const char *banner =
        "o================================================o\n" \
        "| WELCOME TO THE DUMMY CONSOLE              v1.0 |\n" \
        "o================================================o\n";
    fprintf(stdout, "%s\n", banner);
}

/*
 * The console program.
 */
void run_console(void) {
    char command[MAX_CMD_LENGTH];

    while (1) {
        if (system("@cls||clear") != EXIT_SUCCESS) {
            fprintf(stderr, "%s: Failed to clear screen.\n", __func__);
            exit(EXIT_FAILURE);
        }
        display_banner();

        fprintf(stdout, "console# ");

        if (fgets(command, sizeof command, stdin) == NULL) {
            fprintf(stderr, "%s: Invalid reception operation.", __func__);
            exit(EXIT_FAILURE);
        }
        // Removing the newline generated by fgets().
        command[strlen(command) - 1] = 0;

        int exit_code = system(command);

        fprintf(stdout, "\n%s: exited with code %d.\n", command, exit_code);
        getchar();
    }
}

int main(void) {
    run_console();
    return EXIT_SUCCESS;
}
